### ISSUE TITLE
Persist sort

### ISSUE THREAD

**Issue by gampleman** [abe33/atom-tablr#14]
Would be nice if hitting save would actually persist the sort I have on the table.

**Comment by abe33** [comment]
Hi @gampleman, sorry for the late reply, I saw your issue but was caught by some fixes required on the minimap.

When you say persisting the sort on save, do you mean saving the file on disk with the current sort applied or just storing the current sort so that tablr can reuses the same setting when opening the file again?

I ask this because I thought deeply about that when implementing the sort feature and was somehow reticent to make the sort modifies the file on disk without the user intending to do so. I was thinking of adding a command to apply the sort on a table so that the rows get saved in the current order.

**Comment by gampleman** [comment]
I mean saving the file. I feel that changing the sort should make the file dirty and should have and undo support. So the actual saving should happen when the user hits the save command.

**Comment by abe33** [comment]
Hi, I'll have some time to implement something for this, what do ou think of having a button next to the column edit action to apply the current sort on the table? This button would only be available if a sort is applied.

**Comment by gampleman** [comment]
Sounds ok to me.
