### ISSUE TITLE
Can't undo sorting

### ISSUE THREAD

**Issue by p0la** [abe33/atom-tablr#23]
Hello, Thanks for the good work! 

When clicking on a column name (say column F), the array will be sorted based on the content of this column, but the file is not considered modified by atom (no modified blue dot indicator in the tab selector) and the undo operation is not working (Ctrl Z does notthing). 

Thanks a lot.

**Comment by abe33** [comment]
That's because the table was not actually modified, it's just a change in the display, if you continue to click on the header cell you will cycle through the different sort (ascending, descending and then no sort again).

As there's no changes in the model there's no action to undo. However, if you apply the sort using the corresponding button then the model will have been changed and the undo will be available.

Hope it helps.

**Comment by p0la** [comment]
Thanks for the fast answer. 
That helps a lot.

**Comment by abe33** [comment]
Can I close the issue then?

**Comment by p0la** [comment]
Sure. 
Thx again
