### ISSUE TITLE
Unknown symbol in all cells

### ISSUE THREAD

**Issue by maxlarsen** [abe33/atom-tablr#33]
In all the .csv files I open, everything works perfectly but I always have these symbols (like three dots in a light grey box) that I can't make sense of:
![selection_015](https://cloud.githubusercontent.com/assets/16719582/13175974/6bfd5fa6-d6dc-11e5-835c-6d56efbcfbc9.png)

**Comment by abe33** [comment]
Hi @maxlarsen, it's to indicates than the content of the cell is bigger than the cell and that a part of it maybe hidden (hence the ellipsis). Since CSS `text-ellipsis` property doesn't work on multiline text I had to find a workaround. 

Are you by chance on a windows computer? I have found that measuring the cell's content was not as sharp on windows than on OSX and linux.

**Comment by maxlarsen** [comment]
Hi, thanks for your answer. I am on ubuntu and the file is a very plain csv like so:

~~~
1858,1924,1,1912,1922
1862,1946,1,1915,1940
1856,1941,1,1916,1939
1857,1945,1,1917,1922
1857,1930,1,1922,1929
1862,1942,1,1923,1937
~~~

In particular, in the screenshot above, the content is not bigger, I am seeing everything.

**Comment by abe33** [comment]
Ok, looks like there's a problem, sometime it can be just triggered by the line height of the cell which is bigger than the cell's height, but I'll have to look for a better way of handling that case.

**Comment by awagner83** [comment]
I am seeing this same issue as well, and I am running OSX.  It's especially distracting with a light background.  For now I've just tinkered with the css to get the "after" content to go away.
