### ISSUE TITLE
.transition is undefined

### ISSUE THREAD

**Issue by dbkaplun** [abe33/atom-tablr#69]
# Steps to reproduce

1. Use [Nucleus Dark UI](https://atom.io/themes/nucleus-dark-ui)
2. Enable tablr

# Expected

Tablr should load successfully.

# Actual
```
Error compiling Less stylesheet: /Users/kaplund/.atom/packages/tablr/styles/tablr.less
Line number: 75
.transition is undefined
```
```
.transition is undefined in /Users/kaplund/.atom/packages/nucleus-dark-ui/styles/buttons.less:75:2

LessError: .transition is undefined
  at /Users/kaplund/.atom/packages/nucleus-dark-ui/styles/buttons.less:75:2
```

See also #50, which Atom mistakenly thinks is the same issue. ("The error was thrown from the tablr package. This issue has already been reported.")

**Comment by abe33** [comment]
This issue seems to come from the fact that I relied on the `buttons.less` file from the theme. It appears the version from nucleus-dark-ui relies on the fact that the mixins it requires are imported beforehand, which is not the case when I import it. I'll remove the import and use the `.btn` class directly in the markup instead.
